/**
 * Knowledge base for the File Anatomy Inspector.
 *
 * Each entry teaches the orchestrator what a file is, who creates it, whether
 * they should read/edit it, and what to ask their AI agent about it.
 *
 * This is a starter set. As more lessons are authored, more entries are
 * added here.
 */

export interface FileAnatomyEntry {
  pattern: RegExp;
  name: string;
  role: string;
  createdBy: string;
  shouldRead: "yes" | "sometimes" | "rarely";
  shouldEdit: "yes" | "sometimes" | "rarely" | "never";
  contains: string;
  questions: string[];
  taughtIn?: string;
  related?: string[];
}

export const fileAnatomyEntries: FileAnatomyEntry[] = [
  {
    pattern: /^package\.json$/,
    name: "package.json",
    role: "Node.js project manifest. Lists name, version, scripts, and all dependencies.",
    createdBy: "npm init, or a framework scaffolder (create-next-app, vite, etc.)",
    shouldRead: "yes",
    shouldEdit: "sometimes",
    contains: "name, version, scripts (test/build/dev), dependencies, devDependencies, type (module/commonjs)",
    questions: [
      "Why did you add this package? What does it do?",
      "Are any dependencies unused?",
      "Why this version range — caret (^), tilde (~), or exact?",
      "Should this be a devDependency instead?",
    ],
    taughtIn: "Lesson 88: npm and package.json explained fully",
    related: ["package-lock.json", "node_modules", ".npmrc"],
  },
  {
    pattern: /^package-lock\.json$/,
    name: "package-lock.json",
    role: "Locks the exact versions of every dependency (and their dependencies) so installs are reproducible.",
    createdBy: "npm install (auto-generated, never write by hand)",
    shouldRead: "rarely",
    shouldEdit: "never",
    contains: "An exhaustive dependency tree with exact resolved versions and integrity hashes.",
    questions: ["Should this be committed? (yes, always)"],
    taughtIn: "Lesson 90: What package-lock.json is",
  },
  {
    pattern: /^\.gitignore$/,
    name: ".gitignore",
    role: "Tells Git which files and folders to never track. Critical for security and clean diffs.",
    createdBy: "Project scaffolder, or written by hand. Almost every project has one.",
    shouldRead: "yes",
    shouldEdit: "sometimes",
    contains: "Patterns for node_modules, build outputs, .env files, OS files (.DS_Store), editor configs.",
    questions: [
      "Is .env excluded? (Critical — must be.)",
      "Is any build artifact accidentally committed?",
      "Should this file be more strict?",
    ],
    taughtIn: "Lesson 32: .gitignore — what to never commit and why",
  },
  {
    pattern: /^\.env(\..+)?$/,
    name: ".env / .env.local / .env.production",
    role: "Holds environment variables — secrets, API keys, configuration that differs per environment.",
    createdBy: "Written by hand. Often copied from .env.example.",
    shouldRead: "yes",
    shouldEdit: "yes",
    contains: "KEY=value pairs. Database URLs, API keys, third-party tokens, feature flags.",
    questions: [
      "Is this file in .gitignore? (Must be — secrets in repo = security incident.)",
      "Is there a .env.example version checked in for new devs?",
      "Are production secrets stored here or in a secret manager?",
    ],
    taughtIn: "Lesson 9: What environment variables are",
    related: [".env.example", ".gitignore"],
  },
  {
    pattern: /^README(\.md)?$/i,
    name: "README.md",
    role: "The project's front page. What it is, how to run it, how to contribute.",
    createdBy: "Created by the author. Best ones are kept up to date.",
    shouldRead: "yes",
    shouldEdit: "sometimes",
    contains: "Description, install instructions, usage examples, license, contribution guide.",
    questions: ["Does it match the actual setup?", "Are the run commands current?"],
    taughtIn: "Lesson 21: The most common files in any project",
  },
  {
    pattern: /^tsconfig(\..+)?\.json$/,
    name: "tsconfig.json",
    role: "TypeScript compiler configuration. Controls strictness, module system, target JS version, paths.",
    createdBy: "tsc --init, or a framework scaffolder.",
    shouldRead: "yes",
    shouldEdit: "sometimes",
    contains: "compilerOptions (strict, target, moduleResolution, paths, jsx), include/exclude patterns.",
    questions: [
      "Is `strict: true`? (Should be — looser settings allow bugs.)",
      "What does `paths` define? (Import aliases like @/*)",
      "Is target appropriate for the runtime?",
    ],
    taughtIn: "Lesson 86: tsconfig.json — what it does",
  },
  {
    pattern: /^next\.config\.(mjs|js|ts)$/,
    name: "next.config.mjs",
    role: "Next.js configuration. Controls build behavior, image domains, redirects, headers, experimental flags.",
    createdBy: "create-next-app, or written by hand.",
    shouldRead: "yes",
    shouldEdit: "sometimes",
    contains: "module.exports / default export with reactStrictMode, images, redirects, headers, etc.",
    questions: [
      "Why is each option here? Necessary or cargo-culted?",
      "Are any experimental flags risky for production?",
    ],
    taughtIn: "Lesson 178: next.config.js — what it controls",
  },
  {
    pattern: /^tailwind\.config\.(js|ts|mjs)$/,
    name: "tailwind.config.ts",
    role: "Tailwind CSS configuration. Defines the design system: colors, fonts, spacing, breakpoints, content scan paths.",
    createdBy: "npx tailwindcss init",
    shouldRead: "yes",
    shouldEdit: "yes",
    contains: "content (which files to scan), theme.extend, plugins, darkMode.",
    questions: [
      "Does the `content` array include every file using Tailwind classes?",
      "Are custom colors in `theme.extend` or overwriting the defaults?",
    ],
    taughtIn: "Lesson 159: What Tailwind CSS is",
  },
  {
    pattern: /^postcss\.config\.(js|mjs|cjs)$/,
    name: "postcss.config.mjs",
    role: "PostCSS plugin pipeline. Almost always: Tailwind + autoprefixer.",
    createdBy: "Tailwind/framework scaffolder.",
    shouldRead: "rarely",
    shouldEdit: "rarely",
    contains: "plugins object — typically { tailwindcss: {}, autoprefixer: {} }",
    questions: ["Is anything unusual in this pipeline?"],
  },
  {
    pattern: /^Dockerfile(\..+)?$/,
    name: "Dockerfile",
    role: "Recipe for building a container image. The 'works on my machine' killer.",
    createdBy: "Written by hand, sometimes scaffolded by `docker init` or a framework.",
    shouldRead: "yes",
    shouldEdit: "sometimes",
    contains: "FROM (base image), WORKDIR, COPY, RUN, ENV, EXPOSE, CMD/ENTRYPOINT.",
    questions: [
      "Is the base image pinned to a specific version (not `latest`)?",
      "Are layers ordered for cache efficiency (deps before source)?",
      "Are secrets accidentally baked into the image?",
      "Is the final image minimal (multi-stage build)?",
    ],
    taughtIn: "Lesson 188: The Dockerfile, line by line",
  },
  {
    pattern: /^docker-compose\.ya?ml$/,
    name: "docker-compose.yml",
    role: "Defines a multi-container app for local dev — usually app + database + cache.",
    createdBy: "Written by hand.",
    shouldRead: "yes",
    shouldEdit: "sometimes",
    contains: "services (each container), volumes, networks, environment, ports, depends_on.",
    questions: [
      "What does each service do?",
      "Are passwords hardcoded or from env vars?",
      "Are volumes persisting the right data?",
    ],
    taughtIn: "Lesson 192: docker-compose.yml — reading the file",
  },
  {
    pattern: /^node_modules$/,
    name: "node_modules/",
    role: "Installed dependencies. Hundreds of folders. Never read, never edit, always .gitignore'd.",
    createdBy: "npm install / pnpm install / yarn install",
    shouldRead: "rarely",
    shouldEdit: "never",
    contains: "Every direct and transitive dependency, plus their node_modules.",
    questions: ["Is this in .gitignore? (Must be.)"],
    taughtIn: "Lesson 88: npm and package.json",
  },
  {
    pattern: /^prisma$/,
    name: "prisma/",
    role: "Prisma ORM directory. Contains the schema and migration files.",
    createdBy: "npx prisma init",
    shouldRead: "yes",
    shouldEdit: "yes",
    contains: "schema.prisma (data model), migrations/ (timestamped SQL files).",
    questions: ["What models exist? Any missing indexes or foreign keys?"],
    taughtIn: "Lesson 113-115: Prisma",
  },
  {
    pattern: /^schema\.prisma$/,
    name: "schema.prisma",
    role: "Prisma data model. Defines every database table, field, and relationship.",
    createdBy: "Written by hand. Edits trigger migrations.",
    shouldRead: "yes",
    shouldEdit: "yes",
    contains: "datasource (DB connection), generator, model definitions with field types and attributes.",
    questions: [
      "Are foreign keys defined for relationships?",
      "Are indexes on commonly queried fields?",
      "Are required vs. optional fields modeled correctly?",
    ],
    taughtIn: "Lesson 114: Reading a Prisma schema file",
  },
  {
    pattern: /^\.github$/,
    name: ".github/",
    role: "GitHub-specific config. Most importantly: workflows/ (CI/CD pipelines).",
    createdBy: "Written by hand.",
    shouldRead: "yes",
    shouldEdit: "sometimes",
    contains: "workflows/ (YAML CI files), ISSUE_TEMPLATE/, PULL_REQUEST_TEMPLATE.md, CODEOWNERS.",
    questions: ["What runs on every PR?", "Are deploy steps gated by tests?"],
    taughtIn: "Lesson 207: GitHub Actions deep dive",
  },
  {
    pattern: /^app$/,
    name: "app/",
    role: "Next.js App Router source. Each subfolder is a route. Special files: layout.tsx, page.tsx, loading.tsx, error.tsx, route.ts.",
    createdBy: "Project scaffolder.",
    shouldRead: "yes",
    shouldEdit: "yes",
    contains: "Layouts, pages, API routes, loading/error boundaries.",
    questions: ["Is the route layout sane?", "Are server vs. client components used appropriately?"],
    taughtIn: "Lesson 175: Pages vs. App Router",
  },
  {
    pattern: /^src$/,
    name: "src/",
    role: "Source code root. Many projects put all hand-written code in src/ to keep the project root clean.",
    createdBy: "Project convention.",
    shouldRead: "yes",
    shouldEdit: "yes",
    contains: "Components, utilities, hooks, types — whatever the project uses.",
    questions: ["What's the folder structure? Domain-based or type-based?"],
    taughtIn: "Lesson 20: What a software project actually is",
  },
  {
    pattern: /^public$/,
    name: "public/",
    role: "Static assets served as-is. Images, fonts, favicon, robots.txt.",
    createdBy: "Project scaffolder.",
    shouldRead: "rarely",
    shouldEdit: "sometimes",
    contains: "Files served at the root URL. /public/logo.png → /logo.png",
    questions: ["Anything sensitive accidentally in here?"],
    taughtIn: "Lesson 20: What a software project actually is",
  },
  {
    pattern: /^\.next$/,
    name: ".next/",
    role: "Next.js build output. Generated, never committed, never edited.",
    createdBy: "next build / next dev",
    shouldRead: "rarely",
    shouldEdit: "never",
    contains: "Compiled JS, optimized assets, build manifests, caches.",
    questions: ["Is this in .gitignore? (Must be.)"],
    taughtIn: "Lesson 23: What a build process is",
  },
  {
    pattern: /^eslint(\.config)?\.(js|mjs|cjs|json)$/,
    name: "eslint.config / .eslintrc",
    role: "ESLint configuration. Linting rules that catch bugs and enforce style.",
    createdBy: "eslint --init, or framework scaffolder.",
    shouldRead: "yes",
    shouldEdit: "sometimes",
    contains: "Extends (preset configs), rules (overrides), parser, plugins.",
    questions: ["Are critical rules disabled?", "Does CI run the linter?"],
    taughtIn: "Phase 3 — JS/TS",
  },
  {
    pattern: /^requirements\.txt$/,
    name: "requirements.txt",
    role: "Python dependency list. The pip equivalent of package.json's dependencies.",
    createdBy: "Written by hand or via `pip freeze`.",
    shouldRead: "yes",
    shouldEdit: "yes",
    contains: "package==version lines, one per dependency.",
    questions: [
      "Are versions pinned?",
      "Are dev dependencies separated (requirements-dev.txt)?",
    ],
    taughtIn: "Lesson 58: pip and requirements.txt",
  },
  {
    pattern: /^pyproject\.toml$/,
    name: "pyproject.toml",
    role: "Modern Python project config — replaces setup.py/requirements.txt for many projects. Used by Poetry, Hatch, uv.",
    createdBy: "Poetry/Hatch/uv init, or hand-written.",
    shouldRead: "yes",
    shouldEdit: "sometimes",
    contains: "[project] metadata, dependencies, build-system, tool configs (ruff, black, pytest).",
    questions: ["What build backend?", "Which tools are configured here?"],
    taughtIn: "Phase 2 — Python",
  },
  {
    pattern: /^venv$|^\.venv$/,
    name: "venv / .venv/",
    role: "Python virtual environment. Isolated dependency install. Never committed.",
    createdBy: "python -m venv .venv",
    shouldRead: "rarely",
    shouldEdit: "never",
    contains: "Project-local Python interpreter and installed packages.",
    questions: ["Is this in .gitignore? (Must be.)"],
    taughtIn: "Lesson 57: Virtual environments",
  },
];

export function lookupFile(filename: string): FileAnatomyEntry | null {
  return fileAnatomyEntries.find((e) => e.pattern.test(filename)) ?? null;
}
