export interface GlossaryEntry {
  term: string;
  /** alt forms / abbreviations */
  aliases?: string[];
  definition: string;
  /** Where it was first introduced */
  taughtIn?: string;
}

/**
 * Starter glossary. Grows as lessons are authored — every term defined in a
 * lesson must appear here.
 */
export const glossary: GlossaryEntry[] = [
  { term: "API", aliases: ["application programming interface"], definition: "A defined way for one piece of software to ask another to do something or hand over data. Behind the scenes it's almost always an HTTP request.", taughtIn: "Lesson 16" },
  { term: "Argument", definition: "A value passed into a function when calling it.", taughtIn: "Lesson 43" },
  { term: "Authentication", aliases: ["authn"], definition: "Proving you are who you say you are. Logging in.", taughtIn: "Lesson 137" },
  { term: "Authorization", aliases: ["authz"], definition: "Deciding what you're allowed to do once authenticated. Permissions.", taughtIn: "Lesson 137" },
  { term: "Backend", definition: "The server-side of an application — runs on a computer the user never sees. Owns the database, business logic, auth, and APIs.", taughtIn: "Lesson 116" },
  { term: "Branch", definition: "An independent line of development in Git. Lets you work on features without disturbing main.", taughtIn: "Lesson 29" },
  { term: "Build", definition: "The process of turning human-written source code into a form the computer can run or serve to users.", taughtIn: "Lesson 23" },
  { term: "Cache", definition: "A fast store for data you've already fetched or computed, so you don't redo work next time.", taughtIn: "Lesson 111" },
  { term: "CDN", aliases: ["content delivery network"], definition: "A global network of servers that holds copies of your static files so users get them from a nearby location.", taughtIn: "Lesson 200" },
  { term: "CI/CD", aliases: ["continuous integration", "continuous deployment"], definition: "Automated pipelines that run tests on every change and (optionally) ship code to production without human button-clicks.", taughtIn: "Lesson 206" },
  { term: "Client", definition: "The program that initiates a request. Usually a browser, mobile app, or another service.", taughtIn: "Lesson 18" },
  { term: "Commit", definition: "A snapshot of your code in Git, with a message describing what changed and why.", taughtIn: "Lesson 27" },
  { term: "Container", definition: "A self-contained, runnable bundle of an application plus everything it depends on. Solves 'works on my machine.'", taughtIn: "Lesson 187" },
  { term: "CORS", aliases: ["cross-origin resource sharing"], definition: "A browser security rule that blocks JS on one domain from calling an API on another, unless the API explicitly allows it.", taughtIn: "Lesson 143" },
  { term: "CPU", definition: "The central processing unit. The chip that actually does the arithmetic and logic in your computer.", taughtIn: "Lesson 1" },
  { term: "Database", definition: "A structured store for application data. The most expensive thing to mess up.", taughtIn: "Lesson 94" },
  { term: "Dependency", definition: "External code your project relies on. Listed in package.json (Node) or requirements.txt (Python).", taughtIn: "Lesson 22" },
  { term: "Dev environment", aliases: ["development environment"], definition: "Where you (or your AI agent) write and test code, before anyone else sees it.", taughtIn: "Lesson 24" },
  { term: "DNS", aliases: ["domain name system"], definition: "The internet's phonebook. Turns a name like google.com into the IP address of a server.", taughtIn: "Lesson 14" },
  { term: "Docker", definition: "The most popular tool for creating and running containers.", taughtIn: "Lesson 186" },
  { term: "DOM", aliases: ["document object model"], definition: "The browser's in-memory representation of a webpage as a tree of nodes that JavaScript can read and modify.", taughtIn: "Lesson 151" },
  { term: "Endpoint", definition: "A single URL on an API that does one thing — e.g. POST /api/users creates a user.", taughtIn: "Lesson 123" },
  { term: "Environment variable", aliases: ["env var"], definition: "A named value the operating system makes available to programs, like API_KEY=abc. Used so the same code works in dev and prod without changes.", taughtIn: "Lesson 9" },
  { term: "ESM", aliases: ["es modules", "es module"], definition: "The modern JavaScript module system — import/export syntax. The standard going forward.", taughtIn: "Lesson 91" },
  { term: "ETL", aliases: ["extract transform load"], definition: "A pipeline that extracts data from a source, transforms it, and loads it into a destination (usually a warehouse).", taughtIn: "Lesson 216" },
  { term: "Filesystem", definition: "How the OS organizes files and directories on a storage device.", taughtIn: "Lesson 3" },
  { term: "Foreign key", definition: "A column in one database table that references the primary key of another, enforcing relationships.", taughtIn: "Lesson 97" },
  { term: "Framework", definition: "A pre-built scaffold with conventions and tools so you don't write every webserver from scratch.", taughtIn: "Lesson 117" },
  { term: "Frontend", definition: "The user-facing part of an app — runs in a browser or mobile device.", taughtIn: "Lesson 18" },
  { term: "Function", definition: "A reusable block of logic. Takes inputs (arguments), optionally returns an output.", taughtIn: "Lesson 43" },
  { term: "Git", definition: "The version control system that tracks every change to your code, lets you branch, merge, and rewind history.", taughtIn: "Lesson 26" },
  { term: "GitHub", definition: "A hosted service for Git repositories. Adds collaboration features: pull requests, issues, actions, code review.", taughtIn: "Lesson 33" },
  { term: "HTTP", aliases: ["hypertext transfer protocol"], definition: "The protocol the web speaks. A client sends a request, a server sends a response.", taughtIn: "Lesson 15" },
  { term: "HTTPS", definition: "HTTP with encryption (TLS). Everything between client and server is unreadable to intermediaries.", taughtIn: "Lesson 238" },
  { term: "Index", definition: "A data structure attached to a database column that makes lookups dramatically faster.", taughtIn: "Lesson 98" },
  { term: "IP address", definition: "A numerical address that identifies a device on a network. Like a phone number for a computer.", taughtIn: "Lesson 14" },
  { term: "JSON", aliases: ["javascript object notation"], definition: "A simple text format for representing structured data. The default API payload format.", taughtIn: "Lesson 59" },
  { term: "JWT", aliases: ["json web token"], definition: "A signed token containing user info. Sent with every authenticated request instead of a session cookie.", taughtIn: "Lesson 139" },
  { term: "Kernel", definition: "The core of the operating system. Manages CPU, memory, and the line between programs and hardware.", taughtIn: "Lesson 2" },
  { term: "Linux", definition: "An open-source operating system kernel. Powers nearly every server on the internet.", taughtIn: "Lesson 179" },
  { term: "localhost", definition: "Your own computer, when referred to over the network. Address: 127.0.0.1.", taughtIn: "Lesson 19" },
  { term: "Merge", definition: "Combining the work in one Git branch into another.", taughtIn: "Lesson 30" },
  { term: "Middleware", definition: "Code that runs between the incoming request and the handler that produces the response. Used for auth, logging, parsing, rate limits.", taughtIn: "Lesson 119" },
  { term: "Migration", definition: "A timestamped script that updates the database schema in a controlled, reversible way.", taughtIn: "Lesson 115" },
  { term: "Module", definition: "A file or package of code you can import into another file.", taughtIn: "Lesson 50" },
  { term: "Node.js", definition: "A runtime that lets you run JavaScript outside the browser — typically on a server.", taughtIn: "Lesson 87" },
  { term: "ORM", aliases: ["object relational mapper"], definition: "A library that lets you query your database with code (objects/methods) instead of raw SQL.", taughtIn: "Lesson 112" },
  { term: "Operating system", aliases: ["OS"], definition: "Software that manages the hardware and runs your programs. macOS, Linux, Windows.", taughtIn: "Lesson 2" },
  { term: "PATH", definition: "An environment variable listing folders the shell searches for executables. Why typing `git` finds Git.", taughtIn: "Lesson 10" },
  { term: "Permission", definition: "Filesystem-level control over who can read, write, or execute a file. Set with chmod / chown on Unix.", taughtIn: "Lesson 11" },
  { term: "Pipe", definition: "Sends the output of one command into another (using |). Composes small tools into big ones.", taughtIn: "Lesson 12" },
  { term: "PostgreSQL", aliases: ["postgres"], definition: "An open-source relational database. The default choice for serious SaaS apps.", taughtIn: "Lesson 107" },
  { term: "Primary key", definition: "A column whose value is unique for every row in a database table. Used to identify rows.", taughtIn: "Lesson 97" },
  { term: "Process", definition: "A running instance of a program, with its own memory and identity.", taughtIn: "Lesson 5" },
  { term: "Production", aliases: ["prod"], definition: "The live environment users actually use. The place where mistakes cost money.", taughtIn: "Lesson 24" },
  { term: "Pull Request", aliases: ["PR"], definition: "A GitHub feature for proposing a change. You push a branch, open a PR, get review, then merge.", taughtIn: "Lesson 35" },
  { term: "RAM", aliases: ["random access memory"], definition: "Fast, volatile memory. Holds running programs and their data. Wiped when power is cut.", taughtIn: "Lesson 1" },
  { term: "REST", aliases: ["representational state transfer"], definition: "The dominant API style: resources at URLs, HTTP verbs to act on them.", taughtIn: "Lesson 121" },
  { term: "Server", definition: "A program (and the computer running it) that waits for and responds to requests.", taughtIn: "Lesson 18" },
  { term: "Shell", definition: "The program that reads commands from the terminal and runs them. bash, zsh, fish.", taughtIn: "Lesson 6" },
  { term: "SSH", aliases: ["secure shell"], definition: "An encrypted way to log into and run commands on a remote server.", taughtIn: "Lesson 185" },
  { term: "SQL", aliases: ["structured query language"], definition: "The language every relational database speaks. SELECT, INSERT, UPDATE, DELETE.", taughtIn: "Lesson 99" },
  { term: "Staging", definition: "An environment that mimics production, used for final testing before release.", taughtIn: "Lesson 24" },
  { term: "Status code", definition: "A 3-digit number an HTTP server returns. 2xx OK, 3xx redirect, 4xx your fault, 5xx server's fault.", taughtIn: "Lesson 17" },
  { term: "Terminal", definition: "The text-only window where you type commands directly to the computer.", taughtIn: "Lesson 6" },
  { term: "TypeScript", definition: "JavaScript with a type system that catches whole categories of bugs before runtime.", taughtIn: "Lesson 81" },
  { term: "URL", aliases: ["uniform resource locator"], definition: "A web address. Schemes, hosts, paths, query strings, fragments.", taughtIn: "Lesson 13" },
  { term: "Version control", definition: "A system that tracks every change to a set of files over time, with branches and history.", taughtIn: "Lesson 25" },
  { term: "Webhook", definition: "An HTTP callback. Service A calls your URL when something happens (payment succeeded, PR opened).", taughtIn: "Lesson 231" },
  { term: "YAML", definition: "A whitespace-significant configuration format. Used heavily in DevOps (CI workflows, K8s manifests).", taughtIn: "Lesson 202" },
];
